use_frameworks!

workspace '../PinLayout.xcworkspace'

target 'PinLayoutSample' do
  project 'PinLayoutSample.xcodeproj'

  # Debug only
  pod 'Reveal-SDK', :configurations => ['Debug']
  pod 'SwiftLint'
end
