source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

use_frameworks!

target 'PinLayout-iOS' do
    #pod 'PinLayout'
    #pod 'PinLayout', :git => 'https://github.com/mirego/PinLayout.git', :commit => 'f29519b08890da144772fe9b082cd6499b5d82c1'
    pod 'PinLayout', :path => '../../..'
end

