use_frameworks!

workspace 'MCSwiftLayoutSample.xcworkspace'

target 'MCSwiftLayoutSample' do
  project 'MCSwiftLayoutSample.xcodeproj'
  #pod 'YogaKit', '~> 1.1'

  # Debug only
    pod 'Reveal-SDK', :configurations => ['Debug']
    pod 'SwiftLint'
end

target 'MCSwiftLayoutTests' do
    project '../MCSwiftLayout.xcodeproj'
    pod 'Quick'
    pod 'Nimble'
end
