# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.com:mirego/MCPodSpecs.git'

project 'PinLayoutPodTester.xcodeproj'

inhibit_all_warnings!

target 'PinLayoutPodTester' do
  use_frameworks!

  pod 'PinLayout'

end
